### ISSUE TITLE
Diagnose video card issue on HERB2

### ISSUE THREAD

**Issue by siddhss5** [personalrobotics/block_sorting#20]
Figure out whether the video card is dead, and if its failure during the demo was caused by a loose contact or due to thermal issues because of HERB2 being too close to the battery.

**Comment by ClintLiddick** [comment]
The video card is working fine now. There was a slight misconfiguration in the BIOS settings that I fixed, but not sure that would cause the issues. I replugged all the connections and that seemed to do the trick. I think it must have been a loose connection, since herb2 is always near the battery, and the card gets used pretty frequently. We're going to start monitoring the temperature however. It's running quite cool right now (28C).
